{
  "hash": "bd4f97b18b471d1f7d0886eb812646b8",
  "result": {
    "engine": "knitr",
    "markdown": "---\npagetitle: \"Cápsula · Introducción a R\"\nformat:\n  revealjs:\n    theme: [default, estilos.scss]\n    slide-number: c/t\n    width: 1280\n    height: 800\n    margin: 0.06\n    center: false\n    transition: none\n    hash-type: number\n    code-copy: true\n    code-overflow: wrap\n    highlight-style: github\n    footer: \"Estrategias de Investigación Cuantitativa 2026 · Cápsula: Introducción a R\"\n    menu: true\n---\n\n\n\n## {.portada}\n\n::: {.portada-top}\n![](img/logo_facso.png)\n\nProf. Pablo Pérez Ahumada<br>\nApoyo docente: Javiera Romo Sánchez<br>\nAyudantes: Valentina Montecinos, Martina Buzio, Javiera Álvarez, Millaray Vergara y Tomás González.\n:::\n\n::: {.portada-curso}\nEstrategias de Investigación<br>Cuantitativa\n:::\n\n::: {.portada-taller}\nIntroducción<br>a R\n:::\n\n::: {.portada-tema}\nCápsula · RStudio, objetos, librerías, bases de datos, tipos de variables y `dplyr`\n:::\n\n## Contenidos\n\n::: ruta\n::: paso-ruta\n**1 · Interfaz de RStudio**\nConsola, script, entorno y proyectos.\n:::\n::: paso-ruta\n**2 · Programación básica**\nR como calculadora, objetos y funciones.\n:::\n::: paso-ruta\n**3 · Librerías**\nInstalar, cargar y el `tidyverse`.\n:::\n::: paso-ruta\n**4 · Bases de datos rectangulares**\nVariables, valores, observaciones. Importar datos.\n:::\n::: paso-ruta\n**5 · Naturaleza de las variables**\nNuméricas, texto, lógicas, factores, `haven_labelled`, `NA`.\n:::\n::: paso-ruta\n**6 · Transformar datos con `dplyr`**\nFiltrar, seleccionar, crear variables y resumir por grupos.\n:::\n:::\n\n<br>\n\n::: nota\nEsta cápsula se basa en **R para Ciencia de Datos** (Wickham y Grolemund), traducción al español: <https://es.r4ds.hadley.nz/>\n:::\n\n## Antes de empezar: crear el proyecto\n\n<!-- ================================================================== -->\n<!-- MÓDULO 1 · INTERFAZ DE RSTUDIO                                      -->\n<!-- ================================================================== -->\n\n## {.seccion}\n\n::: seccion-texto\nMódulo 1<br>La interfaz de RStudio\n:::\n\n## R y RStudio: ¿cuál es la diferencia?\n\n::: modulo\nMódulo 1 · Interfaz\n:::\n\n:::: {.columns}\n::: {.column width=\"50%\"}\n### R\n\n- Un **lenguaje de programación** para analizar datos.\n- Es el que hace los cálculos.\n- Gratuito y de código abierto.\n:::\n::: {.column width=\"50%\"}\n### RStudio\n\n- Un **entorno de trabajo** para usar R.\n- Organiza el código, los datos, los gráficos y la ayuda.\n- Hay que instalar **los dos**: primero R, luego RStudio.\n:::\n::::\n\n<br>\n\n::: grande\nR es lo que usamos; RStudio es solo la interfaz.\n:::\n\n## Los cuatro paneles de RStudio\n\n::: modulo\nMódulo 1 · Interfaz\n:::\n\n::: paneles\n::: panel\n**1 · Editor (script)**\nDonde escribimos y **guardamos** el código. Es nuestro cuaderno de trabajo.\n:::\n::: panel\n**3 · Entorno (Environment)**\nMuestra los **objetos** que hemos creado: bases de datos, vectores, resultados.\n:::\n::: panel\n**2 · Consola**\nDonde R **ejecuta** el código y muestra los resultados.\n:::\n::: panel\n**4 · Archivos / Gráficos / Paquetes / Ayuda**\nNavegar carpetas, ver gráficos, revisar paquetes instalados y leer la ayuda.\n:::\n:::\n\n## La consola\n\n::: modulo\nMódulo 1 · Interfaz\n:::\n\nPodemos escribir código directamente en la consola y presionar **Enter**:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n2 + 2\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 4\n```\n\n\n:::\n:::\n\n\n- El símbolo **`>`** indica que R está listo para recibir una instrucción.\n- Si aparece **`+`**, R está esperando que terminemos la instrucción (falta cerrar un paréntesis o una comilla). Se sale con **Esc**.\n- El `[1]` indica que el resultado empieza en el primer elemento.\n\n::: alerta\nLo que escribimos en la consola **no queda guardado**. Sirve para probar cosas rápidas, no para trabajar.\n:::\n\n## El script\n\n::: modulo\nMódulo 1 · Interfaz\n:::\n\nUn script es un **archivo de texto con extensión `.R`** donde escribimos el código para poder guardarlo, corregirlo y volver a ejecutarlo.\n\n- Nuevo script: **File → New File → R Script** (`Ctrl + Shift + N`).\n- Ejecutar una línea o selección: **`Ctrl + Enter`** (en Mac: `Cmd + Enter`).\n- Ejecutar todo el script: **`Ctrl + Shift + Enter`**.\n- Todo lo que va después de **`#`** es un **comentario**: R no lo ejecuta.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Esto es un comentario: sirve para explicar qué hace el código\n3 * 5   # también se puede comentar al final de una línea\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 15\n```\n\n\n:::\n:::\n\n\n::: nota\nEl script es la **fuente de verdad** de nuestro análisis: cualquier persona debería poder abrirlo y obtener los mismos resultados.\n:::\n\n## El entorno (Environment)\n\n::: modulo\nMódulo 1 · Interfaz\n:::\n\n- Muestra todos los **objetos** que existen en nuestra sesión de R.\n- Si cerramos RStudio, el entorno se borra y es justamente lo que buscamos. Lo importante es guardar el script.\n\n<br>\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrm(list = ls())   # borra todos los objetos del entorno\n```\n:::\n\n\n## Proyectos de RStudio\n\n::: modulo\nMódulo 1 · Interfaz\n:::\n\nUn **proyecto** (`.Rproj`) es una carpeta que reúne todo lo de un análisis. Al abrirlo, R sabe **dónde estamos trabajando** (el *directorio de trabajo*).\n\n:::: {.columns}\n::: {.column width=\"45%\"}\n```\nintro_R/\n├── intro_R.Rproj\n├── input/    datos originales\n├── script/   código\n└── output/   resultados\n```\n:::\n::: {.column width=\"55%\"}\n- Siempre abrimos el trabajo **haciendo doble clic en el `.Rproj`**.\n- Así R sabe en qué carpeta estamos trabajando para poder buscar la base de datos y para saber dónde guardar lo que le pidamos.\n- Esto permite que el código funcione igual en cualquier computador.\n:::\n::::\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngetwd()   # ¿en qué carpeta estoy trabajando?\n```\n:::\n\n\n\n<!-- ================================================================== -->\n<!-- MÓDULO 2 · PROGRAMACIÓN BÁSICA                                      -->\n<!-- ================================================================== -->\n\n## {.seccion}\n\n::: seccion-texto\nMódulo 2<br>Programación básica\n:::\n\n## R como calculadora\n\n::: modulo\nMódulo 2 · Programación básica\n:::\n\n:::: {.columns}\n::: {.column width=\"50%\"}\n\n::: {.cell}\n\n```{.r .cell-code}\n10 + 5      # suma\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 15\n```\n\n\n:::\n\n```{.r .cell-code}\n10 - 5      # resta\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 5\n```\n\n\n:::\n\n```{.r .cell-code}\n10 * 5      # multiplicación\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 50\n```\n\n\n:::\n\n```{.r .cell-code}\n10 / 4      # división\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 2.5\n```\n\n\n:::\n\n```{.r .cell-code}\n2 ^ 3       # potencia\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 8\n```\n\n\n:::\n:::\n\n:::\n::: {.column width=\"50%\"}\n\n::: {.cell}\n\n```{.r .cell-code}\n(5.5 + 6.2) / 2   # paréntesis primero\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 5.85\n```\n\n\n:::\n\n```{.r .cell-code}\nsqrt(16)          # raíz cuadrada\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 4\n```\n\n\n:::\n:::\n\n\n::: nota\nR respeta el orden de las operaciones: paréntesis, potencias, multiplicación y división, suma y resta.\n:::\n\n::: alerta\nEn R los decimales se escriben con **punto**: `5.5`, no `5,5`.\n:::\n:::\n::::\n\n## Crear objetos\n\n::: modulo\nMódulo 2 · Programación básica\n:::\n\nGuardamos un valor en un **objeto** con el operador de asignación **`<-`**:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnota_mate <- 5.5\nnota_leng <- 6.2\n```\n:::\n\n\nSe lee: *\"`nota_mate` recibe el valor 5.5\"*. El objeto aparece en el **Entorno**. Para ver su contenido, escribimos su nombre:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnota_mate\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 5.5\n```\n\n\n:::\n\n```{.r .cell-code}\npromedio <- (nota_mate + nota_leng) / 2\npromedio\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 5.85\n```\n\n\n:::\n:::\n\n\n::: nota\n**Atajo:** `Alt + -` escribe `<-` (en Mac: `Option + -`).\n:::\n\n## Vectores: varios valores en un objeto\n\n::: modulo\nMódulo 2 · Programación básica\n:::\n\nCon la función **`c()`** (de *combinar*) creamos un **vector**: un conjunto de valores del mismo tipo.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnotas_curso <- c(5.5, 6.2, 4.8, 3.9, 6.7)\nnotas_curso\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 5.5 6.2 4.8 3.9 6.7\n```\n\n\n:::\n\n```{.r .cell-code}\nnotas_curso + 0.5   # la operación se aplica a cada elemento\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 6.0 6.7 5.3 4.4 7.2\n```\n\n\n:::\n\n```{.r .cell-code}\nlength(notas_curso) # ¿cuántos valores tiene?\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 5\n```\n\n\n:::\n:::\n\n\n::: nota\n**Idea clave para lo que viene:** una variable de una base de datos es un vector.\n:::\n\n## Funciones\n\n::: modulo\nMódulo 2 · Programación básica\n:::\n\nUna **función** recibe uno o más valores (*argumentos*), hace algo con ellos y devuelve un resultado.\n\n::: formula\n`nombre_funcion(argumento1 = valor1, argumento2 = valor2)`\n:::\n\n:::: {.columns}\n::: {.column width=\"50%\"}\n\n::: {.cell}\n\n```{.r .cell-code}\nmean(notas_curso)     # promedio\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 5.42\n```\n\n\n:::\n\n```{.r .cell-code}\nmedian(notas_curso)   # mediana\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 5.5\n```\n\n\n:::\n:::\n\n:::\n::: {.column width=\"50%\"}\n\n::: {.cell}\n\n```{.r .cell-code}\nmax(notas_curso)      # máximo\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 6.7\n```\n\n\n:::\n\n```{.r .cell-code}\nround(4.8667, 1)      # redondear\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 4.9\n```\n\n\n:::\n:::\n\n:::\n::::\n\n## Argumentos y ayuda\n\n::: modulo\nMódulo 2 · Programación básica\n:::\n\nLos argumentos se pueden dar **por nombre** o **por posición**:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nround(x = 4.8667, digits = 2)   # por nombre\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 4.87\n```\n\n\n:::\n\n```{.r .cell-code}\nround(4.8667, 2)                # por posición (mismo resultado)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 4.87\n```\n\n\n:::\n\n```{.r .cell-code}\nseq(from = 1, to = 7, by = 0.5) # secuencia del 1 al 7, de 0,5 en 0,5\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n [1] 1.0 1.5 2.0 2.5 3.0 3.5 4.0 4.5 5.0 5.5 6.0 6.5 7.0\n```\n\n\n:::\n:::\n\n\nPara saber qué argumentos tiene una función, pedimos ayuda:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n?round        # abre la ayuda en el panel 4\nhelp(mean)    # lo mismo\n```\n:::\n\n\n## Los errores son parte del proceso\n\n::: modulo\nMódulo 2 · Programación básica\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\nNota_mate          # R distingue mayúsculas: este objeto no existe\n```\n\n::: {.cell-output .cell-output-error}\n\n```\nError: objeto 'Nota_mate' no encontrado\n```\n\n\n:::\n:::\n\n\n```r\nmean(notas_curso   # falta cerrar el paréntesis: la consola muestra \"+\" y espera\n```\n\n\n::: {.cell}\n\n```{.r .cell-code}\n\"5.5\" + 1          # no se puede sumar texto con números\n```\n\n::: {.cell-output .cell-output-error}\n\n```\nError in \"5.5\" + 1: argumento no-numérico para operador binario\n```\n\n\n:::\n:::\n\n\n::: nota\nLean el mensaje de error: casi siempre dice qué pasó. Los más comunes son **errores de tipeo**, **paréntesis o comillas sin cerrar** y **objetos que no se han creado**.\n:::\n\n<!-- ================================================================== -->\n<!-- MÓDULO 3 · LIBRERÍAS                                                -->\n<!-- ================================================================== -->\n\n## {.seccion}\n\n::: seccion-texto\nMódulo 3<br>Librerías (paquetes)\n:::\n\n## ¿Qué es un paquete?\n\n::: modulo\nMódulo 3 · Librerías\n:::\n\n- R trae muchas funciones de base (*R base*): `mean()`, `round()`, `c()`...\n- Los **paquetes** (o librerías) son **extensiones** creadas por la comunidad que agregan funciones nuevas.\n- Se descargan desde **CRAN**, el repositorio oficial de R (hay más de 20.000).\n\n<br>\n\n| Paquete | Para qué sirve |\n|---|---|\n| `readxl` | Abrir archivos de Excel |\n| `haven` | Abrir bases de SPSS, Stata y SAS |\n| `dplyr` | Transformar datos |\n| `ggplot2` | Hacer gráficos |\n\n## Instalar vs. cargar\n\n::: modulo\nMódulo 3 · Librerías\n:::\n\n:::: {.columns}\n::: {.column width=\"50%\"}\n### Instalar: **una sola vez**\n\n\n::: {.cell}\n\n```{.r .cell-code}\ninstall.packages(\"readxl\")\n```\n:::\n\n\nDescarga el paquete al computador. El nombre va **entre comillas**.\n:::\n::: {.column width=\"50%\"}\n### Cargar: **cada sesión**\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(readxl)\n```\n:::\n\n\nDeja disponibles sus funciones mientras R esté abierto.\n:::\n::::\n\n<br>\n\n::: grande\nInstalar es comprar el libro. Cargar es sacarlo de la estantería.\n:::\n\n## El `tidyverse`\n\n::: modulo\nMódulo 3 · Librerías\n:::\n\nUna **colección de paquetes** diseñados para trabajar juntos en ciencia de datos. Es la base de *R para Ciencia de Datos*.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ninstall.packages(\"tidyverse\")   # una vez\nlibrary(tidyverse)              # cada sesión\n```\n:::\n\n\n```\n── Attaching core tidyverse packages ─────────────────── tidyverse 2.0.0 ──\n✔ dplyr     1.1.4     ✔ readr     2.1.5\n✔ forcats   1.0.0     ✔ stringr   1.5.1\n✔ ggplot2   3.5.1     ✔ tibble    3.2.1\n✔ lubridate 1.9.3     ✔ tidyr     1.3.1\n✔ purrr     1.0.2\n── Conflicts ───────────────────────────────────── tidyverse_conflicts() ──\n✖ dplyr::filter() masks stats::filter()\n```\n\n::: nota\nLos **conflictos** avisan que dos paquetes tienen funciones con el mismo nombre. No es un error.\n:::\n\n## `pacman`: instalar y cargar en un paso\n\n::: modulo\nMódulo 3 · Librerías\n:::\n\nCuando usamos varios paquetes, `pacman::p_load()` **instala los que falten y carga todos**:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ninstall.packages(\"pacman\")   # solo la primera vez\n\npacman::p_load(tidyverse,   # manipulación de datos y gráficos\n               readxl,      # abrir archivos de Excel\n               haven)       # variables etiquetadas (SPSS, Stata)\n```\n:::\n\n\n<br>\n\n::: nota\nEsta es la forma que usaremos al inicio de cada script del curso.\n:::\n\n## La notación `paquete::funcion()`\n\n::: modulo\nMódulo 3 · Librerías\n:::\n\nCon **`::`** podemos usar una función de un paquete **sin cargarlo completo**, o dejar claro de dónde viene:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nreadxl::read_excel(\"input/notas_colegio.xlsx\")\ndplyr::filter(notas, curso == \"2°A\")\n```\n:::\n\n\n<br>\n\n¿Cuándo es útil?\n\n- Cuando usamos **una sola función** de un paquete.\n- Cuando hay **conflictos** (dos paquetes con funciones del mismo nombre).\n- Para que otras personas sepan de dónde viene cada función.\n\n<!-- ================================================================== -->\n<!-- MÓDULO 4 · BASES DE DATOS RECTANGULARES                             -->\n<!-- ================================================================== -->\n\n## {.seccion}\n\n::: seccion-texto\nMódulo 4<br>Bases de datos rectangulares\n:::\n\n## Nuestra base de datos\n\n::: modulo\nMódulo 4 · Bases de datos\n:::\n\nNotas de **98 estudiantes** de dos cursos de un colegio (2°A y 2°B). Datos **ficticios**.\n\n| Variable | Descripción | Valores |\n|---|---|---|\n| `id` | Identificador del estudiante | 1 a 98 |\n| `curso` | Curso | 2°A, 2°B |\n| `genero` | Género | Femenino, Masculino |\n| `edad` | Edad en años | 15 a 17 |\n| `nota_matematicas` | Promedio anual en Matemáticas | 1,5 a 7,0 · **888** = No rindió · **999** = Sin información |\n| `nota_lenguaje` | Promedio anual en Lenguaje | 1,5 a 7,0 · **888** = No rindió · **999** = Sin información |\n\n::: nota\nLa hoja `libro_codigos` del Excel tiene esta misma descripción. **Siempre** hay que revisar el libro de códigos antes de analizar una base.\n:::\n\n## Variable, valor y observación\n\n::: modulo\nMódulo 4 · Bases de datos\n:::\n\n```{=html}\n<table class=\"anatomia\">\n<thead><tr><th>id</th><th>curso</th><th class=\"col-resaltada\" style=\"color:#222\">genero</th><th>edad</th><th>nota_matematicas</th><th>nota_lenguaje</th></tr></thead>\n<tbody>\n<tr><td>1</td><td>2°A</td><td class=\"col-resaltada\">Masculino</td><td>16</td><td>6.0</td><td>5.7</td></tr>\n<tr class=\"fila-resaltada\"><td>2</td><td>2°A</td><td class=\"col-resaltada\">Masculino</td><td>16</td><td class=\"celda-resaltada\">4.7</td><td>5.3</td></tr>\n<tr><td>3</td><td>2°A</td><td class=\"col-resaltada\">Masculino</td><td>16</td><td>5.1</td><td>5.2</td></tr>\n<tr><td>4</td><td>2°A</td><td class=\"col-resaltada\">Masculino</td><td>17</td><td>6.1</td><td>5.0</td></tr>\n<tr><td>5</td><td>2°A</td><td class=\"col-resaltada\">Femenino</td><td>15</td><td>4.1</td><td>6.7</td></tr>\n</tbody></table>\n```\n\n::: leyenda\n[Variable: una característica que medimos (columna)]{style=\"background:#fff3c4\"}\n[Observación: la unidad que medimos (fila)]{style=\"background:#dbe7ff\"}\n[Valor: lo que registramos (celda)]{style=\"background:#ffd1cf\"}\n:::\n\n::: chico\n- Una **variable** es una cantidad, cualidad o propiedad que se puede medir: el género, la nota en Matemáticas.\n- Un **valor** es el estado de una variable al medirla: la nota en Matemáticas del estudiante 2 es **4.7**.\n- Una **observación** es un conjunto de mediciones hechas sobre la misma unidad: todo lo que sabemos del estudiante 2.\n:::\n\n## Datos ordenados (*tidy data*)\n\n::: modulo\nMódulo 4 · Bases de datos\n:::\n\nSegún *R para Ciencia de Datos* (cap. 12), una base está **ordenada** cuando cumple tres reglas:\n\n<br>\n\n::: grande\n1. Cada **variable** tiene su propia **columna**.\n2. Cada **observación** tiene su propia **fila**.\n3. Cada **valor** tiene su propia **celda**.\n:::\n\n<br>\n\n::: nota\nNuestra base de notas está ordenada: cada fila es un estudiante y cada columna una característica suya. Por eso se le llama **base rectangular**.\n:::\n\n## ¿Ordenada o desordenada?\n\n::: modulo\nMódulo 4 · Bases de datos\n:::\n\n:::: {.columns}\n::: {.column width=\"50%\"}\n**Desordenada**: el curso está \"escondido\" en los nombres de las columnas.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndesordenada <- tribble(\n  ~estudiante, ~mate_2A, ~mate_2B,\n  \"Ana\",        6.1,      NA,\n  \"Benja\",      NA,       5.4,\n  \"Carla\",      4.9,      NA\n)\ndesordenada\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 3\n  estudiante mate_2A mate_2B\n  <chr>        <dbl>   <dbl>\n1 Ana            6.1    NA  \n2 Benja         NA       5.4\n3 Carla          4.9    NA  \n```\n\n\n:::\n:::\n\n:::\n::: {.column width=\"50%\"}\n**Ordenada**: `curso` es una variable con su propia columna.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nordenada <- tribble(\n  ~estudiante, ~curso, ~nota_mate,\n  \"Ana\",       \"2°A\",   6.1,\n  \"Benja\",     \"2°B\",   5.4,\n  \"Carla\",     \"2°A\",   4.9\n)\nordenada\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 3\n  estudiante curso nota_mate\n  <chr>      <chr>     <dbl>\n1 Ana        2°A         6.1\n2 Benja      2°B         5.4\n3 Carla      2°A         4.9\n```\n\n\n:::\n:::\n\n:::\n::::\n\n## El *data frame*\n\n::: modulo\nMódulo 4 · Bases de datos\n:::\n\nEn R, una base rectangular se guarda como un **data frame**: un conjunto de **vectores del mismo largo**, uno por columna.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nestudiante <- c(\"Ana\", \"Benja\", \"Carla\")\ncurso      <- c(\"2°A\", \"2°B\", \"2°A\")\nnota_mate  <- c(6.1, 5.4, 4.9)\n\nmi_base <- data.frame(estudiante, curso, nota_mate)\nmi_base\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  estudiante curso nota_mate\n1        Ana   2°A       6.1\n2      Benja   2°B       5.4\n3      Carla   2°A       4.9\n```\n\n\n:::\n:::\n\n\n::: nota\nCada columna es un vector (Módulo 2). Todas deben tener **la misma cantidad de valores**: uno por observación.\n:::\n\n## *Tibbles*: data frames modernos\n\n::: modulo\nMódulo 4 · Bases de datos\n:::\n\nEl `tidyverse` usa **tibbles** (cap. 10): data frames que se imprimen de forma más ordenada.\n\n:::: {.columns}\n::: {.column width=\"50%\"}\n\n::: {.cell}\n\n```{.r .cell-code}\ntibble(\n  estudiante = c(\"Ana\", \"Benja\", \"Carla\"),\n  curso      = c(\"2°A\", \"2°B\", \"2°A\"),\n  nota_mate  = c(6.1, 5.4, 4.9)\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 3\n  estudiante curso nota_mate\n  <chr>      <chr>     <dbl>\n1 Ana        2°A         6.1\n2 Benja      2°B         5.4\n3 Carla      2°A         4.9\n```\n\n\n:::\n:::\n\n:::\n::: {.column width=\"50%\"}\nAl imprimir un tibble vemos:\n\n- El **número de filas y columnas** (`3 x 3`).\n- El **tipo** de cada variable bajo su nombre: `<chr>` texto, `<dbl>` número.\n- Solo las primeras 10 filas (no inunda la consola).\n\n\n::: {.cell}\n\n```{.r .cell-code}\nas_tibble(mi_base)   # convierte un data frame en tibble\n```\n:::\n\n:::\n::::\n\n## Importar datos desde Excel\n\n::: modulo\nMódulo 4 · Bases de datos\n:::\n\nRara vez escribimos los datos a mano. Más bien, los **importamos** desde un archivo. Para Excel usamos `read_excel()` del paquete `readxl`:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(readxl)\nnotas <- read_excel(\"input/notas_colegio.xlsx\")\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnotas\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 98 × 6\n      id curso genero     edad nota_matematicas nota_lenguaje\n   <dbl> <chr> <chr>     <dbl>            <dbl>         <dbl>\n 1     1 2°A   Masculino    16              6             5.7\n 2     2 2°A   Masculino    16              4.7           5.3\n 3     3 2°A   Masculino    16              5.1           5.2\n 4     4 2°A   Masculino    17              6.1           5  \n 5     5 2°A   Femenino     15              4.1           6.7\n 6     6 2°A   Femenino     16              5.1           6.1\n 7     7 2°A   Masculino    15            888             6.7\n 8     8 2°A   Femenino     16              7             6.8\n 9     9 2°A   Femenino     17              4.2           6.3\n10    10 2°A   Femenino     16              4.4           5.6\n# ℹ 88 more rows\n```\n\n\n:::\n:::\n\n\n::: chico\nLa ruta es **relativa** al proyecto: `input/` es la carpeta y `notas_colegio.xlsx` el archivo. `read_excel()` lee la primera hoja; con `sheet = \"libro_codigos\"` podemos leer otra.\n:::\n\n## Explorar la base\n\n::: modulo\nMódulo 4 · Bases de datos\n:::\n\n:::: {.columns}\n::: {.column width=\"50%\"}\n\n::: {.cell}\n\n```{.r .cell-code}\ndim(notas)     # filas y columnas\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 98  6\n```\n\n\n:::\n\n```{.r .cell-code}\nnrow(notas)    # n° de observaciones\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 98\n```\n\n\n:::\n\n```{.r .cell-code}\nncol(notas)    # n° de variables\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 6\n```\n\n\n:::\n\n```{.r .cell-code}\nnames(notas)   # nombres de las variables\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"id\"               \"curso\"            \"genero\"           \"edad\"            \n[5] \"nota_matematicas\" \"nota_lenguaje\"   \n```\n\n\n:::\n:::\n\n:::\n::: {.column width=\"50%\"}\n\n::: {.cell}\n\n```{.r .cell-code}\nglimpse(notas) # resumen de cada variable\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 98\nColumns: 6\n$ id               <dbl> 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16…\n$ curso            <chr> \"2°A\", \"2°A\", \"2°A\", \"2°A\", \"2°A\", \"2°A\", \"2°A\", \"2°A…\n$ genero           <chr> \"Masculino\", \"Masculino\", \"Masculino\", \"Masculino\", \"…\n$ edad             <dbl> 16, 16, 16, 17, 15, 16, 15, 16, 17, 16, 15, 16, 16, 1…\n$ nota_matematicas <dbl> 6.0, 4.7, 5.1, 6.1, 4.1, 5.1, 888.0, 7.0, 4.2, 4.4, 4…\n$ nota_lenguaje    <dbl> 5.7, 5.3, 5.2, 5.0, 6.7, 6.1, 6.7, 6.8, 6.3, 5.6, 6.6…\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nView(notas)    # abre la base como planilla\n```\n:::\n\n:::\n::::\n\n## Acceder a una variable con `$`\n\n::: modulo\nMódulo 4 · Bases de datos\n:::\n\nCon **`base$variable`** extraemos una columna. El resultado es un **vector**:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnotas$edad\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n [1] 16 16 16 17 15 16 15 16 17 16 15 16 16 15 16 16 16 15 15 16 17 16 16 16 17\n[26] 16 15 16 16 16 17 15 16 16 16 16 16 16 16 17 17 16 15 16 16 15 16 16 15 15\n[51] 17 16 16 16 16 16 16 16 16 16 16 16 16 16 16 16 16 16 17 15 15 17 16 17 16\n[76] 16 17 17 15 16 17 16 15 17 16 16 15 16 16 16 16 16 16 15 15 15 16 17\n```\n\n\n:::\n\n```{.r .cell-code}\nmean(notas$edad)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 15.95918\n```\n\n\n:::\n\n```{.r .cell-code}\ntable(notas$curso)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n2°A 2°B \n 49  49 \n```\n\n\n:::\n:::\n\n\n::: nota\n`table()` cuenta cuántas veces aparece cada valor: hay **49** estudiantes en cada curso.\n:::\n\n## Importar otros formatos\n\n::: modulo\nMódulo 4 · Bases de datos\n:::\n\n| Formato | Extensión | Función | Paquete |\n|---|---|---|---|\n| Excel | `.xlsx`, `.xls` | `read_excel()` | `readxl` |\n| Texto separado por comas | `.csv` | `read_csv()` | `readr` (tidyverse) |\n| SPSS | `.sav` | `read_sav()` | `haven` |\n| Stata | `.dta` | `read_dta()` | `haven` |\n| R | `.rds` | `readRDS()` | R base |\n\n\n::: {.cell}\n\n```{.r .cell-code}\nencuesta <- read_sav(\"input/encuesta.sav\")       # ejemplo con SPSS\ncasen    <- readRDS(\"input/casen_2024_practico.rds\")\n```\n:::\n\n\n\n<!-- ================================================================== -->\n<!-- MÓDULO 5 · NATURALEZA DE LAS VARIABLES                              -->\n<!-- ================================================================== -->\n\n## {.seccion}\n\n::: seccion-texto\nMódulo 5<br>Naturaleza de las variables\n:::\n\n## Tipos de datos en R\n\n::: modulo\nMódulo 5 · Variables\n:::\n\n| Tipo | En el tibble | Ejemplo | Uso típico |\n|---|---|---|---|\n| Numérico (*double*) | `<dbl>` | `5.5`, `16` | Notas, edad, ingresos |\n| Entero (*integer*) | `<int>` | `16L` | Conteos |\n| Texto (*character*) | `<chr>` | `\"Femenino\"` | Nombres, respuestas abiertas |\n| Lógico (*logical*) | `<lgl>` | `TRUE`, `FALSE` | Resultados de comparaciones |\n| Factor | `<fct>` | `Femenino` (nivel 1) | Variables categóricas |\n| Etiquetado | `<dbl+lbl>` | `888 [No rindió]` | Bases de SPSS / Stata |\n\n\n::: {.cell}\n\n```{.r .cell-code}\nclass(notas$genero)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"character\"\n```\n\n\n:::\n\n```{.r .cell-code}\nclass(notas$nota_matematicas)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"numeric\"\n```\n\n\n:::\n:::\n\n\n## Variables numéricas\n\n::: modulo\nMódulo 5 · Variables\n:::\n\nCon ellas podemos hacer **operaciones matemáticas**: sumar, promediar, calcular desviaciones.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(notas$edad)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. \n  15.00   16.00   16.00   15.96   16.00   17.00 \n```\n\n\n:::\n:::\n\n\n<br>\n\n::: alerta\n**Cuidado:** que una variable esté guardada como número no significa que sea cuantitativa. Si `genero` estuviera codificada como `1 = Femenino` y `2 = Masculino`, su \"promedio\" (por ejemplo, 1,5) **no tendría ningún sentido**. Siempre hay que revisar el libro de códigos.\n:::\n\n## Variables de texto (*character*)\n\n::: modulo\nMódulo 5 · Variables\n:::\n\nGuardan **texto**, siempre entre comillas. No se pueden promediar, pero sí **contar**:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhead(notas$genero)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"Masculino\" \"Masculino\" \"Masculino\" \"Masculino\" \"Femenino\"  \"Femenino\" \n```\n\n\n:::\n\n```{.r .cell-code}\ntable(notas$genero)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n Femenino Masculino \n       49        49 \n```\n\n\n:::\n:::\n\n\n::: chico\nPara R, `\"Femenino\"`, `\"femenino\"` y `\"FEMENINO\"` son tres valores **distintos**. Esto es frecuente en respuestas abiertas o bases mal digitadas.\n:::\n\n## Variables lógicas\n\n::: modulo\nMódulo 5 · Variables\n:::\n\nSolo toman los valores **`TRUE`** (verdadero) o **`FALSE`** (falso). Aparecen cuando hacemos **comparaciones**:\n\n:::: {.columns}\n::: {.column width=\"45%\"}\n| Operador | Significa |\n|---|---|\n| `==` | igual a |\n| `!=` | distinto de |\n| `>`, `>=` | mayor (o igual) |\n| `<`, `<=` | menor (o igual) |\n:::\n::: {.column width=\"55%\"}\n\n::: {.cell}\n\n```{.r .cell-code}\n5.5 >= 4\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] TRUE\n```\n\n\n:::\n\n```{.r .cell-code}\n\"2°A\" == \"2°B\"\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] FALSE\n```\n\n\n:::\n\n```{.r .cell-code}\nhead(notas$nota_lenguaje >= 4)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] TRUE TRUE TRUE TRUE TRUE TRUE\n```\n\n\n:::\n:::\n\n:::\n::::\n\n::: nota\nSe usan muchísimo para **filtrar** casos (módulo 6). Además, `TRUE` vale 1 y `FALSE` vale 0, por lo que `mean()` de un vector lógico da una **proporción**.\n:::\n\n## Factores: variables categóricas\n\n::: modulo\nMódulo 5 · Variables\n:::\n\nUn **factor** es una variable categórica con un conjunto fijo de **niveles** (*levels*) (cap. 15).\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngenero_f <- factor(notas$genero)\nlevels(genero_f)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"Femenino\"  \"Masculino\"\n```\n\n\n:::\n:::\n\n\nLos factores permiten definir un **orden** que no sea el alfabético, útil para variables **ordinales**:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnivel <- c(\"Medio\", \"Bajo\", \"Alto\", \"Medio\")\nfactor(nivel)                                          # orden alfabético\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] Medio Bajo  Alto  Medio\nLevels: Alto Bajo Medio\n```\n\n\n:::\n\n```{.r .cell-code}\nfactor(nivel, levels = c(\"Bajo\", \"Medio\", \"Alto\"))     # orden con sentido\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] Medio Bajo  Alto  Medio\nLevels: Bajo Medio Alto\n```\n\n\n:::\n:::\n\n\n## Valores perdidos: `NA`\n\n::: modulo\nMódulo 5 · Variables\n:::\n\nEn R, un dato faltante se representa con **`NA`** (*Not Available*). Es \"contagioso\": cualquier operación con un `NA` da `NA`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnotas_ejemplo <- c(5.5, NA, 6.1, 4.8)\nmean(notas_ejemplo)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] NA\n```\n\n\n:::\n\n```{.r .cell-code}\nmean(notas_ejemplo, na.rm = TRUE)   # na.rm = TRUE: ignora los NA\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 5.466667\n```\n\n\n:::\n\n```{.r .cell-code}\nis.na(notas_ejemplo)                # ¿qué valores son NA?\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] FALSE  TRUE FALSE FALSE\n```\n\n\n:::\n:::\n\n\n::: nota\nUn `NA` no es un cero: significa **\"no sabemos\"** cuál es el valor.\n:::\n\n## El problema de los códigos 888 y 999\n\n::: modulo\nMódulo 5 · Variables\n:::\n\nEn nuestra base, los datos perdidos **no** están como `NA`, sino como **888** (*No rindió*) y **999** (*Sin información*). ¿Qué pasa si calculamos el promedio directamente?\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmean(notas$nota_matematicas)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 33.38163\n```\n\n\n:::\n\n```{.r .cell-code}\nmean(notas$nota_lenguaje)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 33.5051\n```\n\n\n:::\n:::\n\n\n::: alerta\nUn promedio de **33** en una escala del 1 al 7. Esto pasa porque para R, 888 y 999 son números como cualquier otro. Antes de analizar, hay que **recodificarlos a `NA`** (lo haremos en el módulo 6).\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntable(notas$nota_matematicas %in% c(888, 999))   # ¿cuántos casos tienen esos códigos?\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nFALSE  TRUE \n   95     3 \n```\n\n\n:::\n:::\n\n\n## Variables etiquetadas: `haven_labelled`\n\n::: modulo\nMódulo 5 · Variables\n:::\n\nLas bases de **SPSS y Stata** guardan **etiquetas**: un texto asociado a cada código. Al importarlas con `haven`, R las lee como `haven_labelled`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnota_etiq <- labelled(c(5.5, 6.1, 888, 4.2, 999),\n                      labels = c(\"No rindió\" = 888, \"Sin información\" = 999))\nnota_etiq\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n<labelled<double>[5]>\n[1]   5.5   6.1 888.0   4.2 999.0\n\nLabels:\n value           label\n   888       No rindió\n   999 Sin información\n```\n\n\n:::\n:::\n\n\n::: nota\nEs lo que veríamos si nuestra base de notas viniera en formato `.sav`. En la CASEN aparecen así casi todas las variables.\n:::\n\n## ¿Qué hacemos con una variable etiquetada?\n\n::: modulo\nMódulo 5 · Variables\n:::\n\n:::: {.columns}\n::: {.column width=\"50%\"}\n**Ver sus etiquetas**\n\n\n::: {.cell}\n\n```{.r .cell-code}\nattr(nota_etiq, \"labels\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n      No rindió Sin información \n            888             999 \n```\n\n\n:::\n:::\n\n\n**Quitar las etiquetas** (queda el número)\n\n\n::: {.cell}\n\n```{.r .cell-code}\nzap_labels(nota_etiq)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1]   5.5   6.1 888.0   4.2 999.0\n```\n\n\n:::\n:::\n\n:::\n::: {.column width=\"50%\"}\n**Convertir a factor** (queda la etiqueta)\n\n\n::: {.cell}\n\n```{.r .cell-code}\nas_factor(nota_etiq)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 5.5             6.1             No rindió       4.2            \n[5] Sin información\nLevels: 4.2 5.5 6.1 No rindió Sin información\n```\n\n\n:::\n:::\n\n:::\n::::\n\n::: nota\nRegla práctica: `zap_labels()` para variables que vamos a **promediar**; `as_factor()` para variables **categóricas** que vamos a contar o comparar.\n:::\n\n## Cambiar el tipo de una variable (coerción)\n\n::: modulo\nMódulo 5 · Variables\n:::\n\nLas funciones `as.*()` transforman un tipo en otro:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nas.numeric(\"5.5\")             # texto a número\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 5.5\n```\n\n\n:::\n\n```{.r .cell-code}\nas.character(16)              # número a texto\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"16\"\n```\n\n\n:::\n\n```{.r .cell-code}\nas.numeric(c(\"6.1\", \"seis\"))  # lo que no es número se vuelve NA\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 6.1  NA\n```\n\n\n:::\n:::\n\n\n::: alerta\nCuidado con `as.numeric()` sobre un **factor**: devuelve el número del nivel, no el valor original.\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\nedades_f <- factor(c(\"17\", \"15\", \"16\"))\nas.numeric(edades_f)                  # ✘ posiciones de los niveles\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 3 1 2\n```\n\n\n:::\n\n```{.r .cell-code}\nas.numeric(as.character(edades_f))    # ✔ valores originales\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 17 15 16\n```\n\n\n:::\n:::\n\n\n<!-- ================================================================== -->\n<!-- MÓDULO 6 · DPLYR                                                    -->\n<!-- ================================================================== -->\n\n## {.seccion}\n\n::: seccion-texto\nMódulo 6<br>Transformar datos con `dplyr`\n:::\n\n## La lógica de `dplyr`\n\n::: modulo\nMódulo 6 · dplyr\n:::\n\n`dplyr` (parte del `tidyverse`) ofrece **verbos** para transformar datos (cap. 5). Todos funcionan igual:\n\n1. El primer argumento es **una base de datos**.\n2. Los siguientes argumentos dicen **qué hacer**, usando los nombres de las variables **sin comillas** y **sin `$`**.\n3. El resultado es **una nueva base de datos**.\n\n| Verbo | Qué hace |\n|---|---|\n| `filter()` | Elige **filas** según una condición |\n| `arrange()` | **Ordena** las filas |\n| `select()` | Elige **columnas** |\n| `rename()` | Cambia **nombres** de columnas |\n| `mutate()` | **Crea o modifica** variables |\n| `group_by()` + `summarise()` | **Resume** por grupos |\n\n## El *pipe*: `%>%`\n\n::: modulo\nMódulo 6 · dplyr\n:::\n\nEl *pipe* toma lo que está a su izquierda y lo pasa como **primer argumento** de la función de la derecha. Se lee **\"y luego\"**.\n\n:::: {.columns}\n::: {.column width=\"50%\"}\n**Sin pipe**: se lee de adentro hacia afuera\n\n\n::: {.cell}\n\n```{.r .cell-code}\nround(mean(c(5.5, 6.2, 4.8)), 1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 5.5\n```\n\n\n:::\n:::\n\n:::\n::: {.column width=\"50%\"}\n**Con pipe**: se lee de izquierda a derecha\n\n\n::: {.cell}\n\n```{.r .cell-code}\nc(5.5, 6.2, 4.8) %>%\n  mean() %>%\n  round(1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 5.5\n```\n\n\n:::\n:::\n\n:::\n::::\n\n<br>\n\n::: nota\n**Atajo:** `Ctrl + Shift + M` escribe `%>%`. También existe el *pipe* nativo de R, `|>`, que funciona igual en casi todos los casos.\n:::\n\n## `filter()`: elegir filas\n\n::: modulo\nMódulo 6 · dplyr\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnotas %>%\n  filter(curso == \"2°A\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 49 × 6\n      id curso genero     edad nota_matematicas nota_lenguaje\n   <dbl> <chr> <chr>     <dbl>            <dbl>         <dbl>\n 1     1 2°A   Masculino    16              6             5.7\n 2     2 2°A   Masculino    16              4.7           5.3\n 3     3 2°A   Masculino    16              5.1           5.2\n 4     4 2°A   Masculino    17              6.1           5  \n 5     5 2°A   Femenino     15              4.1           6.7\n 6     6 2°A   Femenino     16              5.1           6.1\n 7     7 2°A   Masculino    15            888             6.7\n 8     8 2°A   Femenino     16              7             6.8\n 9     9 2°A   Femenino     17              4.2           6.3\n10    10 2°A   Femenino     16              4.4           5.6\n# ℹ 39 more rows\n```\n\n\n:::\n:::\n\n\n## `filter()` con varias condiciones\n\n::: modulo\nMódulo 6 · dplyr\n:::\n\n:::: {.columns}\n::: {.column width=\"50%\"}\n**Y** (`&` o coma): se cumplen **ambas**\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnotas %>%\n  filter(curso == \"2°B\" &\n         genero == \"Femenino\") %>%\n  nrow()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 24\n```\n\n\n:::\n:::\n\n\n**O** (`|`): se cumple **al menos una**\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnotas %>%\n  filter(edad == 15 | edad == 17) %>%\n  nrow()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 36\n```\n\n\n:::\n:::\n\n:::\n::: {.column width=\"50%\"}\n**`%in%`**: el valor está en una lista\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnotas %>%\n  filter(nota_matematicas %in% c(888, 999)) %>%\n  select(id, curso, nota_matematicas)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 3\n     id curso nota_matematicas\n  <dbl> <chr>            <dbl>\n1     7 2°A                888\n2    73 2°B                999\n3    91 2°B                888\n```\n\n\n:::\n:::\n\n:::\n::::\n\n## `arrange()`: ordenar filas\n\n::: modulo\nMódulo 6 · dplyr\n:::\n\n:::: {.columns}\n::: {.column width=\"50%\"}\nDe menor a mayor\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnotas %>%\n  arrange(nota_lenguaje) %>%\n  select(id, genero, nota_lenguaje) %>%\n  head(4)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 4 × 3\n     id genero    nota_lenguaje\n  <dbl> <chr>             <dbl>\n1    40 Masculino           3.3\n2    80 Masculino           3.4\n3    63 Masculino           3.6\n4    41 Masculino           3.7\n```\n\n\n:::\n:::\n\n:::\n::: {.column width=\"50%\"}\nDe mayor a menor, con `desc()`\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnotas %>%\n  arrange(desc(nota_lenguaje)) %>%\n  select(id, genero, nota_lenguaje) %>%\n  head(4)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 4 × 3\n     id genero    nota_lenguaje\n  <dbl> <chr>             <dbl>\n1    22 Masculino           999\n2    39 Masculino           888\n3    58 Masculino           888\n4    26 Femenino              7\n```\n\n\n:::\n:::\n\n:::\n::::\n\n## `select()`: elegir columnas\n\n::: modulo\nMódulo 6 · dplyr\n:::\n\n:::: {.columns}\n::: {.column width=\"50%\"}\nPor nombre\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnotas %>%\n  select(id, genero, nota_lenguaje) %>%\n  head(3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 3\n     id genero    nota_lenguaje\n  <dbl> <chr>             <dbl>\n1     1 Masculino           5.7\n2     2 Masculino           5.3\n3     3 Masculino           5.2\n```\n\n\n:::\n:::\n\n\nCon funciones de ayuda\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnotas %>%\n  select(id, starts_with(\"nota_\")) %>%\n  head(3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 3\n     id nota_matematicas nota_lenguaje\n  <dbl>            <dbl>         <dbl>\n1     1              6             5.7\n2     2              4.7           5.3\n3     3              5.1           5.2\n```\n\n\n:::\n:::\n\n:::\n::: {.column width=\"50%\"}\nQuitar columnas con `-`\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnotas %>%\n  select(-curso, -edad, -nota_matematicas) %>%\n  head(3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 3\n     id genero    nota_lenguaje\n  <dbl> <chr>             <dbl>\n1     1 Masculino           5.7\n2     2 Masculino           5.3\n3     3 Masculino           5.2\n```\n\n\n:::\n:::\n\n\n::: chico\nOtras funciones de ayuda: `ends_with()`, `contains()`, `everything()`.\n:::\n:::\n::::\n\n## `rename()`: cambiar nombres\n\n::: modulo\nMódulo 6 · dplyr\n:::\n\nLa sintaxis es **`nombre_nuevo = nombre_viejo`**:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnotas %>%\n  rename(mate = nota_matematicas,\n         leng = nota_lenguaje) %>%\n  head(3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 6\n     id curso genero     edad  mate  leng\n  <dbl> <chr> <chr>     <dbl> <dbl> <dbl>\n1     1 2°A   Masculino    16   6     5.7\n2     2 2°A   Masculino    16   4.7   5.3\n3     3 2°A   Masculino    16   5.1   5.2\n```\n\n\n:::\n:::\n\n\n::: nota\nNombres cortos y sin espacios ni tildes facilitan el trabajo. Ojo: si no guardamos el resultado con `<-`, la base original **no cambia**.\n:::\n\n## `mutate()`: recodificar 888 y 999 a `NA`\n\n::: modulo\nMódulo 6 · dplyr\n:::\n\n`mutate()` crea o modifica variables. Con `if_else()` reemplazamos los códigos por `NA`:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnotas <- notas %>%\n  mutate(nota_matematicas = if_else(nota_matematicas %in% c(888, 999), NA, nota_matematicas),\n         nota_lenguaje    = if_else(nota_lenguaje    %in% c(888, 999), NA, nota_lenguaje))\n\nsummary(notas$nota_matematicas)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max.    NA's \n  3.300   4.700   5.100   5.225   5.800   7.000       3 \n```\n\n\n:::\n:::\n\n\n::: chico\n`if_else(condición, valor si es verdadero, valor si es falso)`. Ahora el máximo es 7 y aparecen los `NA's`.\n:::\n\n::: nota\nEsta vez **sí guardamos** el resultado con `notas <-`: la base queda corregida para lo que sigue.\n:::\n\n## `mutate()`: crear variables nuevas\n\n::: modulo\nMódulo 6 · dplyr\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnotas <- notas %>%\n  mutate(promedio   = (nota_matematicas + nota_lenguaje) / 2,\n         aprueba_mate = if_else(nota_matematicas >= 4, \"Aprueba\", \"Reprueba\"),\n         genero     = factor(genero))\n\nnotas %>%\n  select(id, genero, nota_matematicas, nota_lenguaje, promedio, aprueba_mate) %>%\n  head(5)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 5 × 6\n     id genero    nota_matematicas nota_lenguaje promedio aprueba_mate\n  <dbl> <fct>                <dbl>         <dbl>    <dbl> <chr>       \n1     1 Masculino              6             5.7     5.85 Aprueba     \n2     2 Masculino              4.7           5.3     5    Aprueba     \n3     3 Masculino              5.1           5.2     5.15 Aprueba     \n4     4 Masculino              6.1           5       5.55 Aprueba     \n5     5 Femenino               4.1           6.7     5.4  Aprueba     \n```\n\n\n:::\n:::\n\n\n## `mutate()` con `case_when()`\n\n::: modulo\nMódulo 6 · dplyr\n:::\n\nPara recodificar en **más de dos categorías**, usamos `case_when()`: cada línea es `condición ~ valor`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnotas <- notas %>%\n  mutate(tramo_lenguaje = case_when(nota_lenguaje <  4   ~ \"Insuficiente\",\n                                    nota_lenguaje <  5.5 ~ \"Suficiente\",\n                                    nota_lenguaje >= 5.5 ~ \"Destacado\",\n                                    TRUE ~ NA_character_)) # Dependiendo de la naturaleza de la variable ponemos NA_real_, NA_complex_, NA_integer_\n\ntable(notas$tramo_lenguaje, useNA = \"ifany\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n   Destacado Insuficiente   Suficiente         <NA> \n          46            6           43            3 \n```\n\n\n:::\n:::\n\n\n::: chico\nLas condiciones se evalúan **en orden**: un 4,8 no cumple la primera, sí la segunda, y ahí se queda. Los `NA` siguen siendo `NA`.\n:::\n\n## `summarise()`: resumir\n\n::: modulo\nMódulo 6 · dplyr\n:::\n\n`summarise()` reduce toda la base a **una fila** con los estadísticos que pidamos:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnotas %>%\n  summarise(n          = n(),\n            media_mate = mean(nota_matematicas, na.rm = TRUE),\n            media_leng = mean(nota_lenguaje, na.rm = TRUE),\n            de_leng    = sd(nota_lenguaje, na.rm = TRUE))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 4\n      n media_mate media_leng de_leng\n  <int>      <dbl>      <dbl>   <dbl>\n1    98       5.23       5.35   0.900\n```\n\n\n:::\n:::\n\n\n::: nota\nAhora que recodificamos los 888 y 999, los promedios **sí tienen sentido**. Y no olvidar `na.rm = TRUE`.\n:::\n\n## `group_by()` + `summarise()`: resumir por grupos\n\n::: modulo\nMódulo 6 · dplyr\n:::\n\nLa combinación más poderosa de `dplyr`: calcular estadísticos **para cada grupo**.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnotas %>%\n  group_by(genero) %>%\n  summarise(n          = n(),\n            media_mate = mean(nota_matematicas, na.rm = TRUE),\n            media_leng = mean(nota_lenguaje, na.rm = TRUE)) %>% \n  ungroup()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 4\n  genero        n media_mate media_leng\n  <fct>     <int>      <dbl>      <dbl>\n1 Femenino     49       4.87       5.66\n2 Masculino    49       5.59       5.03\n```\n\n\n:::\n:::\n\n\n::: grande\n¿Qué observan?\n:::\n\n## Agrupar por más de una variable\n\n::: modulo\nMódulo 6 · dplyr\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnotas %>%\n  group_by(curso, genero) %>%\n  summarise(media_mate = round(mean(nota_matematicas, na.rm = TRUE), 2),\n            media_leng = round(mean(nota_lenguaje, na.rm = TRUE), 2),\n            .groups = \"drop\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 4 × 4\n  curso genero    media_mate media_leng\n  <chr> <fct>          <dbl>      <dbl>\n1 2°A   Femenino        4.9        5.73\n2 2°A   Masculino       5.4        5.03\n3 2°B   Femenino        4.83       5.58\n4 2°B   Masculino       5.78       5.03\n```\n\n\n:::\n:::\n\n\n::: nota\nEn **ambos cursos** los hombres tienen mejores notas en Matemáticas y las mujeres en Lenguaje. ¿Cómo podríamos explicar sociológicamente estas brechas?\n:::\n\n## `count()`: contar casos\n\n::: modulo\nMódulo 6 · dplyr\n:::\n\n`count()` es un atajo para `group_by()` + `summarise(n = n())`:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnotas %>%\n  count(genero, aprueba_mate)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 3\n  genero    aprueba_mate     n\n  <fct>     <chr>        <int>\n1 Femenino  Aprueba         45\n2 Femenino  Reprueba         3\n3 Femenino  <NA>             1\n4 Masculino Aprueba         46\n5 Masculino Reprueba         1\n6 Masculino <NA>             2\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnotas %>%\n  filter(!is.na(aprueba_mate)) %>%\n  group_by(genero) %>%\n  summarise(pct_aprueba = mean(aprueba_mate == \"Aprueba\") * 100)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 2\n  genero    pct_aprueba\n  <fct>           <dbl>\n1 Femenino         93.8\n2 Masculino        97.9\n```\n\n\n:::\n:::\n\n\n## Todo junto: una pregunta de investigación\n\n::: modulo\nMódulo 6 · dplyr\n:::\n\n**¿Las brechas de género en las notas son iguales en ambos cursos?**\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbrechas <- notas %>%\n  filter(!is.na(nota_matematicas), !is.na(nota_lenguaje)) %>%   # solo casos válidos\n  group_by(curso, genero) %>%                                   # por curso y género\n  summarise(n = n(),\n            mate = mean(nota_matematicas),\n            leng = mean(nota_lenguaje),\n            .groups = \"drop\") %>%\n  mutate(diferencia = round(mate - leng, 2)) %>%                # mate - lenguaje\n  arrange(curso, desc(diferencia))\n\nbrechas\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 4 × 6\n  curso genero        n  mate  leng diferencia\n  <chr> <fct>     <int> <dbl> <dbl>      <dbl>\n1 2°A   Masculino    21  5.32  4.95       0.37\n2 2°A   Femenino     25  4.90  5.73      -0.83\n3 2°B   Masculino    23  5.80  5.02       0.79\n4 2°B   Femenino     23  4.83  5.57      -0.74\n```\n\n\n:::\n:::\n\n\n## Un adelanto: visualizar la brecha\n\n::: modulo\nMódulo 6 · dplyr\n:::\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](index_files/figure-revealjs/grafico-1.png){fig-align='center' width=1056}\n:::\n:::\n\n\n\n## Guardar resultados en `output/`\n\n::: modulo\nMódulo 6 · dplyr\n:::\n\nLos resultados se guardan en la carpeta **`output/`**, nunca sobre los datos originales de `input/`:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nwrite_csv(brechas, \"output/brechas_genero.csv\")   # tabla de resultados\nsaveRDS(notas, \"output/notas_limpia.rds\")         # base limpia, para seguir trabajando\n```\n:::\n\n\n<br>\n\n::: nota\nAsí, la carpeta `input/` siempre conserva los datos **tal como los recibimos**, y cualquier persona puede reproducir el análisis corriendo el script desde el principio.\n:::\n\n\n## Resumen\n\n::: modulo\nCierre\n:::\n\n| Módulo | Lo central |\n|---|---|\n| 1 · RStudio | Trabajar **siempre** en un script, dentro de un proyecto |\n| 2 · Programación | `objeto <- valor`; `funcion(argumentos)`; `c()` crea vectores |\n| 3 · Librerías | `install.packages()` una vez; `library()` o `p_load()` cada sesión |\n| 4 · Bases de datos | Fila = observación, columna = variable, celda = valor |\n| 5 · Variables | Revisar el tipo; `NA`, códigos perdidos y etiquetas |\n| 6 · `dplyr` | `filter`, `select`, `mutate`, `group_by` + `summarise`, unidos con `%>%` |\n\n## Para seguir aprendiendo\n\n<br>\n\n- **R para Ciencia de Datos** (en español): <https://es.r4ds.hadley.nz/>\n  - Cap. 4 y 6: flujo de trabajo y scripts\n  - Cap. 5: transformación de datos con `dplyr`\n  - Cap. 10 a 12: tibbles, importación y datos ordenados\n  - Cap. 15: factores\n- Documentación de `haven`: <https://haven.tidyverse.org/>\n- Hoja de referencia de `dplyr` (*cheatsheet*): **Help → Cheat Sheets** en RStudio\n\n<br>\n\n",
    "supporting": [
      "index_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-after-body": [
        "\n<script>\n  // htmlwidgets need to know to resize themselves when slides are shown/hidden.\n  // Fire the \"slideenter\" event (handled by htmlwidgets.js) when the current\n  // slide changes (different for each slide format).\n  (function () {\n    // dispatch for htmlwidgets\n    function fireSlideEnter() {\n      const event = window.document.createEvent(\"Event\");\n      event.initEvent(\"slideenter\", true, true);\n      window.document.dispatchEvent(event);\n    }\n\n    function fireSlideChanged(previousSlide, currentSlide) {\n      fireSlideEnter();\n\n      // dispatch for shiny\n      if (window.jQuery) {\n        if (previousSlide) {\n          window.jQuery(previousSlide).trigger(\"hidden\");\n        }\n        if (currentSlide) {\n          window.jQuery(currentSlide).trigger(\"shown\");\n        }\n      }\n    }\n\n    // hookup for slidy\n    if (window.w3c_slidy) {\n      window.w3c_slidy.add_observer(function (slide_num) {\n        // slide_num starts at position 1\n        fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);\n      });\n    }\n\n  })();\n</script>\n\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}